version: '3.8'

volumes:
  jenkins-docker-certs:
  jenkins:

services:
  jenkins:
    container_name: jenkins
    image: jenkins-blueocean
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - ENV=dev-
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    hostname: jenkins
    restart: always
    volumes:
      - jenkins:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - /home/senese/pricetracker:/pricetracker:ro
    depends_on:
      - docker

  docker:
    container_name: docker-dind
    image: docker:dind
    ports:
      - 2376:2376
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    privileged: true
    hostname: docker
    restart: always
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins:/var/jenkins_home

